title: VocVach-Blog
description: "---> FxQ4nt <----"
author:
  name: "FxQ4nt"
  email: "ducta.qc@gmail.com"
  url: "https://vocvach.xyz"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "FxQ4nt"
year : "2020"